package cloud.autotests.tests;

import cloud.autotests.helpers.DriverUtils;
import com.codeborne.selenide.CollectionCondition;
import com.codeborne.selenide.Condition;
import io.qameta.allure.Description;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.Keys;

import static cloud.autotests.helpers.TestData.*;
import static com.codeborne.selenide.Selectors.byText;
import static com.codeborne.selenide.Selenide.*;
import static io.qameta.allure.Allure.step;
import static org.assertj.core.api.Assertions.assertThat;


public class GeneratedTests extends TestBase {

    @Test
    @Description("Autogenerated test")
    @DisplayName("Page console log should not have errors")
    void consoleShouldNotHaveErrorsTest() {
        step("Open url 'https://stepik.org'", () ->
                open("https://stepik.org"));

        step("Console logs should not contain text 'SEVERE'", () -> {
            String consoleLogs = DriverUtils.getConsoleLogs();
            String errorText = "SEVERE";

            assertThat(consoleLogs).doesNotContain(errorText);
        });
    }

    @Test
    @Description("Page title should have header text")
    @DisplayName("Page title test")
    void titleTest() {
        step("Open url 'https://stepik.org/''", () ->
                open("https://stepik.org/"));

        step("Catalog - Stepik", () -> {
            String expectedTitle = "Catalog — Stepik";
            String actualTitle = title();

            assertThat(actualTitle).isEqualTo(expectedTitle);
        });
    }

    @Test()
    @Description("New user should be registered")
    @DisplayName("Registration test")
    void shouldRegistrationTest() {
        step("open 'https://stepik.org/'", () -> {
            open("https://stepik.org/");
        });
        step("Press button 'Register'", () -> {
            $(By.id("ember193")).click();
        });
        step("Fill the field: name, email, password", () -> {
            $(By.id("id_registration_full-name")).setValue(generateName);
            $(By.id("id_registration_email")).setValue(generateEmail);
            $(By.id("id_registration_password")).setValue(generatePassword);
        });
        step("Confirm registration", () -> {
            $x("//button[@type='submit']").click();
        });
        step("Display icon with profile", () -> {
            $x("//button[@aria-label='Profile']").shouldBe(Condition.exist);
        });
    }

    @Test()
    @Description("User should be authorized")
    @DisplayName("Authorization test")
    void authorizationTest() {
        step("open 'https://stepik.org/'", () -> {
            open("https://stepik.org/");
        });
        step("Press button 'Log In'", () -> {
            $(By.id("ember192")).click();
        });
        step("Fill the field: name, email, password", () -> {
            $(By.id("id_login_email")).setValue("Terminator666@gmail.com");
            $(By.id("id_login_password")).setValue("terminator666");
        });
        step("Confirm authorization", () -> {
            $x("//button[@type='submit']").click();
        });
        step("Display icon with profile", () -> {
            $x("//button[@aria-label='Profile']").shouldBe(Condition.exist);
        });
    }

    @Test()
    @Description("User should logout")
    @DisplayName("Logout test")
    void shouldLogOutTest() {
        step("open 'https://stepik.org/'", () -> {
            open("https://stepik.org/");
        });
        step("Press button 'Log In'", () -> {
            $(By.id("ember192")).click();
        });
        step("Fill the field: name, email, password", () -> {
            $(By.id("id_login_email")).setValue("Terminator666@gmail.com");
            $(By.id("id_login_password")).setValue("terminator666");
        });
        step("Confirm authorization", () -> {
            $x("//button[@type='submit']").click();
        });
        step("Display actions in the profile action", () -> {
            $x("//button[@aria-label='Profile']").click();
        });
        step("Click logout action", () -> {
            $(byText("Logout")).click();
        });
        step("Confirmation action", () -> {
            $(byText("OK")).click();
        });
        step("Display authorization/registration window", () -> {
            $(".sign-form__input-group").shouldBe(Condition.visible);
            $(By.id("ember434")).shouldBe(Condition.visible).shouldBe(Condition.text("Log in"));
            $x(("//a[@data-tab-name='registration']")).shouldBe(Condition.visible).shouldBe(Condition.text("Register"));
        });
    }

    @Test()
    @Description("Interface should be changed by different languages")
    @DisplayName("Change language interface")
    void shouldChangeLanguageInterface() {
        step("open 'https://stepik.org/'", () -> {
            open("https://stepik.org/");
        });
        step("Press button languages", () -> {
            $(By.id("ember191")).click();
            int i = 0;
            while (i < $$x("//li[@class='menu-item']").size()) {
                $$x("//li[@class='menu-item']").get(i).click();
                switch (i) {
                    case 0:
                        String placeholderBe = $x("//input[@placeholder='Пошук…']").getAttribute("placeholder");
                        assertThat(placeholderBe).isEqualTo("Пошук…");
                        break;
                    case 1:
                        String placeholderDe = $x("//input[@placeholder='Suchen']").getAttribute("placeholder");
                        assertThat(placeholderDe).isEqualTo("Suchen");
                        break;
                    case 2:
                        String placeholderEn = $x("//input[@placeholder='Search']").getAttribute("placeholder");
                        assertThat(placeholderEn).isEqualTo("Search");
                        break;
                    case 3:
                        String placeholderEs = $x("//input[@placeholder='Escribe para buscar']").getAttribute("placeholder");
                        assertThat(placeholderEs).isEqualTo("Escribe para buscar");
                        break;
                    case 4:
                        String placeholderPt = $x("//input[@placeholder='Procurar']").getAttribute("placeholder");
                        assertThat(placeholderPt).isEqualTo("Procurar");
                        break;
                    case 5:
                        String placeholderRu = $x("//input[@placeholder='Поиск…']").getAttribute("placeholder");
                        assertThat(placeholderRu).isEqualTo("Поиск…");
                        break;
                    case 6:
                        String placeholderUk = $x("//input[@placeholder='Пошук...']").getAttribute("placeholder");
                        assertThat(placeholderUk).isEqualTo("Пошук...");
                        break;
                    case 7:
                        String placeholderZh = $x("//input[@placeholder='键入要搜索']").getAttribute("placeholder");
                        assertThat(placeholderZh).isEqualTo("键入要搜索");
                        break;
                }
                i++;
                $(By.id("ember191")).click();
            }
        });
    }

    @Test()
    @Description("User should find results")
    @DisplayName("Search field")
    void shouldFindResultsFromSearch() {
        step("open 'https://stepik.org/'", () -> {
            open("https://stepik.org/");
        });
        step("Input 'Java' in search field", () -> {
            $(".search-form__input ").setValue("Java");
            $(".search-form__submit").click();
            $(".search-form__input ").sendKeys(Keys.ENTER);
        });
        step(" results with 'Java' are exist and visible and the first result contains Java", () -> {
            $$(".course-cards__item").shouldHave(CollectionCondition.sizeGreaterThan(0));
            String javaWord = "Java";
            String text = String.format("Легкий старт в %s. Вводный курс для чайников", javaWord);
            $$(".course-card__title").get(0).shouldHave(Condition.text(text));
        });
    }

    @Test()
    @Description("User should find results by filters")
    @DisplayName("Search results by filters")
    void shouldFindResultsByFilters() {
        step("open 'https://stepik.org/'", () -> {
            open("https://stepik.org/");
        });
        step("Choose filters: english language, with cert and Free", () -> {
            $(".search-form__input ").setValue("Java");
            $(".search-form__input ").sendKeys(Keys.ENTER);
            $(".select-box__toggle-btn").click();
            $$(".select-box__option").get(1).click();
            $(byText("With certificate")).click();
            $(byText("Free")).click();
        });
        step("Press 'Search' button", () -> {
            $(".search-form__submit").click();
        });
        step(" results with 'Java' are exist and visible and the first result contains Java", () -> {
            $$(".course-cards__item").shouldHave(CollectionCondition.sizeGreaterThan(0));
            String javaWord = "Java";
            String text = String.format("%s. Базовый курс", javaWord);
            $$(".course-card__title").get(0).shouldHave(Condition.text(text));
            String certificate = $x("//div[@class='course-card__widgets'][1]//span[@data-type='certificate']")
                    .getAttribute("aria-label");
            String price = $$(".format-price_free").get(0).getText();
            Assertions.assertEquals("This course issues a certificate", certificate);
            Assertions.assertEquals("Free", price);
        });
    }


}